from enum import StrEnum


class ConversationStage(StrEnum):
    IDLE = "IDLE"
    COLLECTING_SERVICE = "COLLECTING_SERVICE"
    COLLECTING_DATE = "COLLECTING_DATE"
    COLLECTING_PERIOD = "COLLECTING_PERIOD"
    SHOWING_SLOT_OPTIONS = "SHOWING_SLOT_OPTIONS"
    COLLECTING_PATIENT_NAME = "COLLECTING_PATIENT_NAME"
    CONFIRMING_APPOINTMENT = "CONFIRMING_APPOINTMENT"
    APPOINTMENT_CREATED = "APPOINTMENT_CREATED"
    CONFIRMING_CANCEL_APPOINTMENT = "CONFIRMING_CANCEL_APPOINTMENT"
    WAITING_HUMAN = "WAITING_HUMAN"


class ConversationIntent(StrEnum):
    BOOK_APPOINTMENT = "book_appointment"
    CANCEL_APPOINTMENT = "cancel_appointment"
    RESCHEDULE_APPOINTMENT = "reschedule_appointment"
    FAQ = "faq"
    HUMAN_HANDOFF = "human_handoff"
